### ISSUE TITLE
Display Grocery List

### ISSUE THREAD

**Issue by btoconnor** [zanix/MMM-MealieMenu#56]
I'm not sure if opening an issue is really the right place for this, and honestly I'm not even convinced this module would be the ideal place for the grocery list functionality, but figured I'd ask.  Let me know if there's a better route for this.

**Is your feature request related to a problem? Please describe.**
I am considering moving our family's grocery list storage to Mealie's shopping list, and I'd like to show the list on our MagicMirror.

**Describe the solution you'd like**
Potentially pulling the configured shopping list from Mealie and displaying it as a list on MagicMirror.

**Describe alternatives you've considered**
A separate integration just for Mealie's shopping list functionality might be more appropriate (though it would overlap considerably with a lot of the code in this module).

**Additional context**
Right now we use Todoist to show our grocery list on the MagicMirror.  This has always been a clunky solution, and was only done in order to utilize the Alexa list features.

As of July 1st, 2024, Amazon has removed 3rd party integration to their native lists, and Todoist appears to not be interested in filling in the gaps with a custom integration.  As I move to figure out a better solution to showcasing our grocery list on the MagicMirror, I decided to look into Mealie's grocery list functionality.  However, as far as I can tell, there's no integration to show a Mealie shopping list on MagicMirror.

**Comment by zanix** [comment]
I actually wanted to add the shopping list as well. I keep going back and forth on making a separate module or add it to this one.

**Comment by zanix** [comment]
That said, I just moved so I won't have time to work on this for a little while.

**Comment by btoconnor** [comment]
No worries at all.  I might take a shot at it once I wrap up the other module I'm finalizing.  If you get around to it before me, I'd be happy to help out wherever I can.

**Comment by btoconnor** [comment]
I've gone ahead and gotten to a place where this works for one shopping list: https://github.com/btoconnor/MMM-MealieShoppingList

It needs a lot of polish and a handful of extra features, but figured it's good enough to get going.  I've been using this locally for a few days now and works as expected.

**Comment by zanix** [comment]
> I've gone ahead and gotten to a place where this works for one shopping list: https://github.com/btoconnor/MMM-MealieShoppingList
> 
> It needs a lot of polish and a handful of extra features, but figured it's good enough to get going. I've been using this locally for a few days now and works as expected.

Awesome! I'll have to check it out.
